"""Generate Unity wire fields and embedded schemas from canonical JSON Schema."""

import json
from pathlib import Path

from scripts.build_contracts import CONTRACTS


def generate() -> str:
    roots = {name: json.loads((CONTRACTS / f"{name.lower()}.v1.schema.json").read_text(encoding="utf-8"))
             for name in ("Tour", "Element", "Bridge")}
    roots["ClearedBridge"] = json.loads((CONTRACTS / "bridge-clear.v1.schema.json").read_text(encoding="utf-8"))
    models = {}
    for schema in roots.values():
        models.update(schema.get("$defs", {}))
        models[schema["title"]] = schema

    def type_name(schema):
        if "$ref" in schema:
            return schema["$ref"].split("/")[-1] + "ContractV1"
        if "anyOf" in schema:
            actual = next(item for item in schema["anyOf"] if item.get("type") != "null")
            result = type_name(actual)
            return result + "?" if result in ("int", "double", "bool") else result
        if schema.get("type") == "array":
            return type_name(schema["items"]) + "[]"
        return {"string": "string", "integer": "int", "number": "double", "boolean": "bool"}[schema["type"]]

    output = "// Generated by API scripts/generate_unity_contracts.py; do not edit.\n"
    output += "using System;\nusing UnityEngine.Scripting;\n\nnamespace MusiyoBetsknate.Museo\n{\n"
    for name, schema in sorted(models.items()):
        output += f"    [Serializable, Preserve]\n    public sealed partial class {name}ContractV1\n    {{\n"
        for field, value in schema["properties"].items():
            output += f"        [Preserve] public {type_name(value)} {field};\n"
        output += "    }\n\n"
    output += "    internal static class ContractSchemasV1\n    {\n"
    for name, schema in roots.items():
        text = json.dumps(schema, ensure_ascii=False, separators=(",", ":")).replace('"', '""')
        output += f'        public const string {name} = @"{text}";\n'
    return output + "    }\n}\n"


if __name__ == "__main__":
    import sys
    destination = Path(__file__).resolve().parents[2] / "Musiyo_Bëtsknaté/Assets/Scripts/Museo/PublicContractModelsV1.cs"
    output = generate()
    if "--check" in sys.argv:
        if destination.read_text(encoding="utf-8") != output:
            raise SystemExit("Generated Unity contracts are stale")
    else:
        destination.write_text(output, encoding="utf-8", newline="\n")
